-- Javora — canonical schema, migration 001.
--
-- PORTABILITY. This DDL is deliberately written to run unchanged on both
-- SQLite and PostgreSQL. That is not fence-sitting: PostgreSQL is the
-- production target, but no PostgreSQL is available in this environment, and
-- a schema that only exists as an untested .sql file proves nothing. Writing
-- portable SQL means the same statements that are exercised here against a
-- real SQLite database are the ones that will run against Postgres.
--
-- The constraints that make that work:
--   * TEXT primary keys. Every id is deterministic and generated by the
--     application (see src/sync/importRun.ts), so no SERIAL/UUID is needed —
--     and determinism is what makes re-import idempotent.
--   * No ENUM types; TEXT plus CHECK constraints, which both engines accept.
--   * No arrays and no JSONB; repeated values live in join tables.
--   * Dates as TEXT holding partial ISO strings ("1968", "2024-09",
--     "1968-11-24") with the precision recorded alongside. A DATE column
--     cannot represent "we only know the year", and widening a year into
--     1968-01-01 is exactly the fabrication this project forbids.
--   * Timestamps as TEXT ISO-8601 UTC.

-- ---------------------------------------------------------------- sources

CREATE TABLE IF NOT EXISTS source (
  id                        TEXT PRIMARY KEY,
  name                      TEXT NOT NULL,
  institution               TEXT NOT NULL,
  source_type               TEXT NOT NULL,
  category                  TEXT NOT NULL,
  url                       TEXT NOT NULL,
  description               TEXT NOT NULL DEFAULT '',
  sync_state                TEXT NOT NULL DEFAULT 'not-connected'
                              CHECK (sync_state IN ('not-connected','manual-import','scheduled','live','failing')),
  -- NULL until a real retrieval happens. Never back-filled to look active.
  last_checked_at           TEXT,
  last_successful_sync_at   TEXT,
  created_at                TEXT NOT NULL,
  updated_at                TEXT NOT NULL
);

-- Authority is per fact type, not a single global ranking: Parliament is
-- primary for who sits in Parliament but not for election returns.
-- `rank` orders competing authorities for the same fact type (1 = highest).
CREATE TABLE IF NOT EXISTS source_authority (
  source_id  TEXT NOT NULL REFERENCES source(id) ON DELETE CASCADE,
  fact_type  TEXT NOT NULL,
  rank       INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (source_id, fact_type)
);

CREATE INDEX IF NOT EXISTS idx_source_authority_fact ON source_authority (fact_type, rank);

-- Raw retrievals. Append-only: a new snapshot never replaces its predecessor,
-- because the predecessor is the only evidence of what the source used to say.
CREATE TABLE IF NOT EXISTS source_snapshot (
  id                 TEXT PRIMARY KEY,
  source_id          TEXT NOT NULL REFERENCES source(id) ON DELETE CASCADE,
  url                TEXT NOT NULL,
  retrieved_at       TEXT NOT NULL,
  -- Hash of the PARSED, canonically ordered records — not of the raw bytes.
  -- parliament.lk embeds a per-request CSRF token, so a raw-byte hash reports
  -- "changed" on every single check and floods the audit trail.
  content_hash       TEXT NOT NULL,
  raw_content_hash   TEXT,
  raw_hash_is_stable INTEGER NOT NULL DEFAULT 0,
  storage_reference  TEXT,
  connector_version  TEXT NOT NULL,
  parser_version     TEXT NOT NULL,
  status             TEXT NOT NULL CHECK (status IN ('ok','fetch-failed','parse-failed')),
  error_message      TEXT,
  record_count       INTEGER
);

CREATE INDEX IF NOT EXISTS idx_snapshot_source_time ON source_snapshot (source_id, retrieved_at DESC);
CREATE INDEX IF NOT EXISTS idx_snapshot_hash        ON source_snapshot (source_id, content_hash);

-- One row per sync attempt, successful or not. A failed run must never erase
-- canonical data; it is recorded here and the last good snapshot stands.
CREATE TABLE IF NOT EXISTS sync_run (
  id             TEXT PRIMARY KEY,
  source_id      TEXT NOT NULL REFERENCES source(id) ON DELETE CASCADE,
  trigger        TEXT NOT NULL CHECK (trigger IN ('scheduled','manual','backfill','retry')),
  started_at     TEXT NOT NULL,
  finished_at    TEXT,
  outcome        TEXT NOT NULL CHECK (outcome IN ('unchanged','applied','dry-run','failed','blocked')),
  snapshot_id    TEXT REFERENCES source_snapshot(id),
  seen_count     INTEGER NOT NULL DEFAULT 0,
  created_count  INTEGER NOT NULL DEFAULT 0,
  updated_count  INTEGER NOT NULL DEFAULT 0,
  unchanged_count INTEGER NOT NULL DEFAULT 0,
  error_message  TEXT
);

CREATE INDEX IF NOT EXISTS idx_sync_run_source ON sync_run (source_id, started_at DESC);

-- ---------------------------------------------------------------- people

CREATE TABLE IF NOT EXISTS person (
  id                  TEXT PRIMARY KEY,
  slug                TEXT NOT NULL UNIQUE,
  canonical_name      TEXT NOT NULL,
  name_en             TEXT NOT NULL,
  name_si             TEXT,
  name_ta             TEXT,
  date_of_birth       TEXT,
  date_of_birth_precision TEXT CHECK (date_of_birth_precision IN ('year','month','day')),
  date_of_death       TEXT,
  date_of_death_precision TEXT CHECK (date_of_death_precision IN ('year','month','day')),
  gender              TEXT,
  biography           TEXT,
  portrait_url        TEXT,
  portrait_source_id  TEXT REFERENCES source(id),
  portrait_credit     TEXT,
  portrait_retrieved_at TEXT,
  verification        TEXT NOT NULL DEFAULT 'unverified',
  verified_at         TEXT,
  -- Demonstration records are kept separable from authoritative ones so the
  -- two can never be silently blended.
  is_demonstration    INTEGER NOT NULL DEFAULT 0,
  created_at          TEXT NOT NULL,
  updated_at          TEXT NOT NULL,

  -- Mirrors the rule enforced in lib/verification.ts: a verification with no
  -- date is not a verification.
  CHECK (verification <> 'verified' OR verified_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_person_name  ON person (canonical_name);
CREATE INDEX IF NOT EXISTS idx_person_slug  ON person (slug);
-- Normalised name for prefix search; populated by the application.
CREATE INDEX IF NOT EXISTS idx_person_demo  ON person (is_demonstration);

CREATE TABLE IF NOT EXISTS person_alias (
  person_id  TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  alias      TEXT NOT NULL,
  -- Lowercased, unpunctuated form used for matching.
  alias_key  TEXT NOT NULL,
  PRIMARY KEY (person_id, alias_key)
);

CREATE INDEX IF NOT EXISTS idx_alias_key ON person_alias (alias_key);

-- The UNIQUE constraint here is what makes automatic identity matching safe:
-- one external id within one source's id-space maps to exactly one person.
CREATE TABLE IF NOT EXISTS person_external_id (
  person_id    TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  source_key   TEXT NOT NULL,
  external_id  TEXT NOT NULL,
  PRIMARY KEY (person_id, source_key),
  UNIQUE (source_key, external_id)
);

CREATE INDEX IF NOT EXISTS idx_external_lookup ON person_external_id (source_key, external_id);

-- Text blob a person is searched against. Kept as a column so search can move
-- to a database index (Postgres tsvector) without changing call sites.
CREATE TABLE IF NOT EXISTS person_search (
  person_id  TEXT PRIMARY KEY REFERENCES person(id) ON DELETE CASCADE,
  search_text TEXT NOT NULL
);

-- ---------------------------------------------------------------- parties

CREATE TABLE IF NOT EXISTS party (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  abbreviation  TEXT NOT NULL DEFAULT '',
  name_si       TEXT,
  name_ta       TEXT,
  founded_date  TEXT,
  dissolved_date TEXT,
  verification  TEXT NOT NULL DEFAULT 'unverified',
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS party_alias (
  party_id   TEXT NOT NULL REFERENCES party(id) ON DELETE CASCADE,
  alias      TEXT NOT NULL,
  alias_key  TEXT NOT NULL,
  PRIMARY KEY (party_id, alias_key)
);

-- Affiliation is history. Changing party closes the old row and inserts a new
-- one; the previous affiliation is never deleted.
CREATE TABLE IF NOT EXISTS political_affiliation (
  id            TEXT PRIMARY KEY,
  person_id     TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  party_id      TEXT NOT NULL REFERENCES party(id),
  role          TEXT NOT NULL DEFAULT 'member',
  start_date    TEXT,
  end_date      TEXT,
  current_as_of TEXT,
  verification  TEXT NOT NULL DEFAULT 'unverified',
  verified_at   TEXT,
  created_at    TEXT NOT NULL,
  updated_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_affiliation_person ON political_affiliation (person_id);
CREATE INDEX IF NOT EXISTS idx_affiliation_party  ON political_affiliation (party_id);

-- ---------------------------------------------------------------- districts

CREATE TABLE IF NOT EXISTS district (
  id        TEXT PRIMARY KEY,
  name      TEXT NOT NULL,
  province  TEXT
);

-- ---------------------------------------------------------------- positions

-- NOTE the absence of an is_current column. Currency is derived from
-- end_date / start_date / current_as_of against the query date, so a stored
-- flag can never drift out of agreement with the dates.
CREATE TABLE IF NOT EXISTS position (
  id                TEXT PRIMARY KEY,
  person_id         TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  title             TEXT NOT NULL,
  role_type         TEXT NOT NULL,
  institution       TEXT NOT NULL,
  ministry          TEXT,
  district_id       TEXT REFERENCES district(id),
  constituency      TEXT,
  start_date        TEXT,
  start_date_precision TEXT CHECK (start_date_precision IN ('year','month','day')),
  end_date          TEXT,
  end_date_precision   TEXT CHECK (end_date_precision IN ('year','month','day')),
  -- A source's dated assertion that the office IS held, for sources that say
  -- "currently holds" without publishing a start date.
  current_as_of     TEXT,
  appointment_type  TEXT NOT NULL DEFAULT 'unknown',
  precedence        INTEGER NOT NULL DEFAULT 99,
  verification      TEXT NOT NULL DEFAULT 'unverified',
  verified_at       TEXT,
  -- Which source's claim this row represents as canonical.
  canonical_source_id TEXT REFERENCES source(id),
  superseded_by     TEXT REFERENCES position(id),
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,

  CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date),
  CHECK (verification <> 'verified' OR verified_at IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS idx_position_person ON position (person_id);
CREATE INDEX IF NOT EXISTS idx_position_role   ON position (role_type);
CREATE INDEX IF NOT EXISTS idx_position_district ON position (district_id);
-- "Which offices are open" without a stored flag.
CREATE INDEX IF NOT EXISTS idx_position_open   ON position (person_id) WHERE end_date IS NULL;
CREATE INDEX IF NOT EXISTS idx_position_dates  ON position (start_date, end_date);

CREATE TABLE IF NOT EXISTS position_event (
  id            TEXT PRIMARY KEY,
  position_id   TEXT REFERENCES position(id) ON DELETE CASCADE,
  person_id     TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  event_type    TEXT NOT NULL,
  event_date    TEXT NOT NULL,
  event_date_precision TEXT CHECK (event_date_precision IN ('year','month','day')),
  title         TEXT NOT NULL,
  description   TEXT,
  verification  TEXT NOT NULL DEFAULT 'unverified',
  verified_at   TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_event_person ON position_event (person_id, event_date DESC);

-- ---------------------------------------------------------------- elections

CREATE TABLE IF NOT EXISTS election (
  id             TEXT PRIMARY KEY,
  slug           TEXT NOT NULL UNIQUE,
  name           TEXT NOT NULL,
  election_type  TEXT NOT NULL,
  election_date  TEXT NOT NULL,
  election_date_precision TEXT CHECK (election_date_precision IN ('year','month','day')),
  term           TEXT,
  verification   TEXT NOT NULL DEFAULT 'unverified',
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_election_date ON election (election_date DESC);

CREATE TABLE IF NOT EXISTS candidacy (
  id               TEXT PRIMARY KEY,
  election_id      TEXT NOT NULL REFERENCES election(id) ON DELETE CASCADE,
  person_id        TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  party_id         TEXT REFERENCES party(id),
  district_id      TEXT REFERENCES district(id),
  result           TEXT NOT NULL DEFAULT 'unknown',
  -- NULL unless an official count is published. Never estimated.
  votes            INTEGER,
  preference_votes INTEGER,
  seat             TEXT,
  verification     TEXT NOT NULL DEFAULT 'unverified',
  created_at       TEXT NOT NULL,

  UNIQUE (election_id, person_id, district_id),
  CHECK (votes IS NULL OR votes >= 0)
);

CREATE INDEX IF NOT EXISTS idx_candidacy_election ON candidacy (election_id);
CREATE INDEX IF NOT EXISTS idx_candidacy_person   ON candidacy (person_id);

-- ---------------------------------------------------------------- qualifications

CREATE TABLE IF NOT EXISTS qualification (
  id             TEXT PRIMARY KEY,
  person_id      TEXT NOT NULL REFERENCES person(id) ON DELETE CASCADE,
  institution    TEXT NOT NULL,
  qualification  TEXT NOT NULL,
  field          TEXT,
  start_date     TEXT,
  end_date       TEXT,
  end_date_precision TEXT CHECK (end_date_precision IN ('year','month','day')),
  verification   TEXT NOT NULL DEFAULT 'unverified',
  verified_at    TEXT,
  created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_qualification_person ON qualification (person_id);

-- ---------------------------------------------------------------- evidence

-- The join between a claim and the document supporting it. A row naming only
-- a source_id (no url, record id or locator) is an institution reference, not
-- a citation, and must not raise a claim above 'unverified'.
CREATE TABLE IF NOT EXISTS source_evidence (
  id               TEXT PRIMARY KEY,
  source_id        TEXT NOT NULL REFERENCES source(id),
  entity_type      TEXT NOT NULL,
  entity_id        TEXT NOT NULL,
  field_name       TEXT,
  source_url       TEXT,
  document_title   TEXT,
  published_at     TEXT,
  retrieved_at     TEXT,
  locator          TEXT,
  source_record_id TEXT,
  content_hash     TEXT,
  snapshot_id      TEXT REFERENCES source_snapshot(id),
  notes            TEXT,
  created_at       TEXT NOT NULL,

  CHECK (source_url IS NULL OR source_url LIKE 'http%')
);

-- Polymorphic parent: no FK is possible, so the composite index carries lookups.
CREATE INDEX IF NOT EXISTS idx_evidence_entity ON source_evidence (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_evidence_source ON source_evidence (source_id);

-- ---------------------------------------------------------------- audit

CREATE TABLE IF NOT EXISTS change_event (
  id                 TEXT PRIMARY KEY,
  entity_type        TEXT NOT NULL,
  entity_id          TEXT NOT NULL,
  field_name         TEXT NOT NULL,
  previous_value     TEXT,
  new_value          TEXT,
  change_kind        TEXT NOT NULL DEFAULT 'field-changed',
  source_id          TEXT REFERENCES source(id),
  source_snapshot_id TEXT REFERENCES source_snapshot(id),
  sync_run_id        TEXT REFERENCES sync_run(id),
  correction_id      TEXT,
  detected_at        TEXT NOT NULL,
  -- Detecting a change is not verifying it. A reviewer sets this.
  verified_at        TEXT,
  actor              TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_change_entity ON change_event (entity_type, entity_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_change_run    ON change_event (sync_run_id);

-- Where uncertain matches go. Names never merge automatically; only an exact
-- external-id match does, and that path never reaches this table.
CREATE TABLE IF NOT EXISTS identity_review (
  id                TEXT PRIMARY KEY,
  incoming_name     TEXT NOT NULL,
  incoming_payload  TEXT NOT NULL,
  candidate_person_id TEXT REFERENCES person(id),
  confidence        TEXT NOT NULL CHECK (confidence IN ('probable','uncertain')),
  signals           TEXT NOT NULL DEFAULT '',
  source_id         TEXT REFERENCES source(id),
  detected_at       TEXT NOT NULL,
  resolved_at       TEXT,
  resolution        TEXT
);

CREATE INDEX IF NOT EXISTS idx_identity_open ON identity_review (detected_at DESC) WHERE resolved_at IS NULL;

-- Disagreements between official sources. Both claims are retained; the
-- record is never resolved by deleting one side.
CREATE TABLE IF NOT EXISTS source_conflict (
  id                TEXT PRIMARY KEY,
  entity_type       TEXT NOT NULL,
  entity_id         TEXT NOT NULL,
  field_name        TEXT NOT NULL,
  fact_type         TEXT NOT NULL,
  source_a_id       TEXT NOT NULL REFERENCES source(id),
  value_a           TEXT,
  evidence_a_id     TEXT REFERENCES source_evidence(id),
  source_b_id       TEXT NOT NULL REFERENCES source(id),
  value_b           TEXT,
  evidence_b_id     TEXT REFERENCES source_evidence(id),
  -- 'authority' when the fact-type authority rules settled it; 'unresolved'
  -- when neither source outranks the other for this fact type.
  resolution_state  TEXT NOT NULL CHECK (resolution_state IN ('unresolved','resolved-by-authority','resolved-by-review')),
  resolved_value    TEXT,
  resolved_source_id TEXT REFERENCES source(id),
  detected_at       TEXT NOT NULL,
  resolved_at       TEXT,
  UNIQUE (entity_type, entity_id, field_name, source_a_id, source_b_id)
);

CREATE INDEX IF NOT EXISTS idx_conflict_entity ON source_conflict (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_conflict_open   ON source_conflict (detected_at DESC) WHERE resolution_state = 'unresolved';

-- ---------------------------------------------------------------- corrections

-- Reader-submitted corrections. These NEVER write canonical data directly;
-- they move through review states first.
CREATE TABLE IF NOT EXISTS correction_report (
  id                    TEXT PRIMARY KEY,
  entity_type           TEXT NOT NULL,
  entity_id             TEXT NOT NULL,
  field_name            TEXT NOT NULL,
  current_value         TEXT,
  proposed_value        TEXT NOT NULL,
  supporting_source_url TEXT NOT NULL,
  explanation           TEXT,
  submitted_at          TEXT NOT NULL,
  submitter_contact     TEXT,
  review_status         TEXT NOT NULL DEFAULT 'open'
                          CHECK (review_status IN ('open','under-review','verified','rejected','published')),
  reviewed_at           TEXT,
  reviewer              TEXT,
  resolution            TEXT,

  CHECK (supporting_source_url LIKE 'http%'),
  -- A decided report must record when and by whom it was decided.
  CHECK (review_status IN ('open','under-review') OR (reviewed_at IS NOT NULL AND reviewer IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS idx_correction_status ON correction_report (review_status, submitted_at DESC);
