/**
 * Javora — consistent SQLite backup (L-7, SECURITY--SL Politics.md §24).
 *
 * `.data/javora.db` is the ONLY copy of the synchronised canonical dataset —
 * `.env.production.example` already warns that an empty file there is
 * indistinguishable from total loss — and until this script existed, nothing
 * in this repository produced a backup of it at all.
 *
 * CONSISTENCY. Uses SQLite's own `VACUUM INTO`, not a filesystem copy. A
 * plain `cp` of a WAL-mode database can copy the main file mid-write and
 * miss what is still sitting in the `-wal`/`-shm` side files, producing a
 * corrupt or torn snapshot; `VACUUM INTO` asks SQLite itself for a
 * transactionally-consistent copy, safe to run against a live database with
 * the sync worker (or anything else) still writing to it, and the source
 * connection is opened read-only here besides — the backup process cannot
 * write to the thing it is backing up even if that were somehow attempted.
 *
 * WHERE BACKUPS GO. `.data/backups/` by default — gitignored (see
 * `.gitignore`'s `.data/` rule), never inside `dist/`, never served by
 * nginx (`deploy/nginx.conf` denies every `.db`/`.db-wal`/`.db-shm`
 * extension outright as defence in depth, and the whole path is outside
 * `root /var/www/javora` regardless). `.data/backups/javora-2026-08-29T21-
 * 01-04-180Z.db` already exists in this convention (CLAUDE.md calls it out
 * as a protected recovery artefact) — this script reproduces exactly that
 * naming, automated.
 *
 * RETENTION AND ENCRYPTION are deliberately NOT this script's job — they are
 * infrastructure decisions (how long, on what disk, under what key) that
 * belong to wherever backups are actually shipped off-host, not hardcoded
 * into a one-shot Node script. See deploy/README.md §5 for the documented
 * retention/encryption/restore-drill procedure this script is one step of.
 *
 * Usage:
 *   node scripts/backup-db.mjs [--out-dir <dir>] [--label <suffix>]
 *
 *   --out-dir   Defaults to .data/backups/ next to the source database.
 *   --label     Optional suffix (e.g. --label pre-migration), matching the
 *               existing manual convention seen in .data/backups/ today.
 */

import { DatabaseSync } from "node:sqlite";
import { mkdirSync, existsSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { DEFAULT_DB_PATH } from "../server/db/database.ts";

function parseArgs(argv) {
  const args = { outDir: null, label: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out-dir") args.outDir = argv[++i];
    else if (argv[i] === "--label") args.label = argv[++i];
  }
  return args;
}

/** javora-2026-08-29T21-01-04-180Z(-label).db — matches the existing manual convention in .data/backups/. */
function backupFilename(label) {
  const stamp = new Date().toISOString().replace(/[:.]/g, "-");
  return `javora-${stamp}${label ? `-${label}` : ""}.db`;
}

export function runBackup({ sourcePath, outDir, label } = {}) {
  const source = sourcePath ?? process.env.JAVORA_DB ?? DEFAULT_DB_PATH;
  if (!existsSync(source)) {
    throw new Error(`backup-db: source database does not exist: ${source}`);
  }

  const destDir = outDir ?? join(dirname(source), "backups");
  mkdirSync(destDir, { recursive: true });

  const destPath = resolve(destDir, backupFilename(label));

  const db = new DatabaseSync(source, { readOnly: true });
  try {
    // VACUUM INTO's target has no bound-parameter form in SQLite; the path
    // is entirely generated by this script (a fixed directory plus a
    // timestamp this process produced itself), never from external input, so
    // escaping the one metacharacter that matters (a literal single quote,
    // which cannot occur in a path this script builds) and inlining it is
    // the same reasoning scripts/provision-postgres-roles.mjs already
    // documents for its own operator-controlled SQL identifiers.
    db.exec(`VACUUM INTO '${destPath.replace(/'/g, "''")}'`);
  } finally {
    db.close();
  }

  const sourceBytes = statSync(source).size;
  const backupBytes = statSync(destPath).size;

  return { source, destPath, sourceBytes, backupBytes };
}

if (
  import.meta.url === `file://${process.argv[1]?.replace(/\\/g, "/")}` ||
  process.argv[1]?.endsWith("backup-db.mjs")
) {
  const args = parseArgs(process.argv.slice(2));
  try {
    const result = runBackup({ outDir: args.outDir, label: args.label });
    console.log(`backup-db: ${result.source} -> ${result.destPath}`);
    console.log(`  source size: ${result.sourceBytes.toLocaleString()} bytes`);
    console.log(`  backup size: ${result.backupBytes.toLocaleString()} bytes`);
  } catch (error) {
    console.error("backup-db: FAILED.");
    console.error(error);
    process.exit(1);
  }
}
